<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');

$config['pre_url'] = "/";

$config['parametre_lang_datable']['SHOW_ENTRIES'] = "Nombre de résultat :";
$config['parametre_lang_datable']['SEARCH'] = "Recherche :";
$config['parametre_lang_datable']['sEmptyTable'] = "Aucune donnée";
$config['parametre_lang_datable']['sLast'] = "Fin";
$config['parametre_lang_datable']['sFirst'] = "Début";
$config['parametre_lang_datable']['sInfoEmpty'] = "0 résultat";
$config['parametre_lang_datable']['sInfo'] = "Affichage _START_ à _END_ sur _TOTAL_ résultats";
$config['parametre_lang_datable']['sInfoFiltered'] = "(filtrée de _MAX_ résultats)";
$config['parametre_lang_datable']['sZeroRecords'] = "Aucun résultat correspondant à votre recherche n&#39;a été trouvé";

$config['parametre_export_datable']['swfUrl'] = $config['pre_url']."static/datatables/copy_csv_xls_pdf.swf";

$config['directory_img_calibre'] = "static/img/calibre";

$config['directory_download'] = "static/download";

$config['directory_upload'] = "static/uploads";

$config['directory_pdf'] = "static/generate_pdf";
$config['directory_pdf'] = "/var/www/vhosts/optieyescommande.com/httpdocs/static/aa";

$config['regions'] = array(
'0' => '',
'75' => 'Ile-de-France',
'77' => 'Ile-de-France',
'78' => 'Ile-de-France',
'91' => 'Ile-de-France',
'92' => 'Ile-de-France',
'93' => 'Ile-de-France',
'94' => 'Ile-de-France',
'95' => 'Ile-de-France',
'51' => 'Champagne-Ardenne',
'08' => 'Champagne-Ardenne',
'10' => 'Champagne-Ardenne',
'52' => 'Champagne-Ardenne',
'80' => 'Picardie',
'02' => 'Picardie',
'60' => 'Picardie',
'76' => 'Haute-Normandie',
'27' => 'Haute-Normandie',
'45' => 'Centre',
'18' => 'Centre',
'28' => 'Centre',
'36' => 'Centre',
'37' => 'Centre',
'41' => 'Centre',
'14' => 'Basse-Normandie',
'50' => 'Basse-Normandie',
'61' => 'Basse-Normandie',
'21' => 'Bourgogne',
'58' => 'Bourgogne',
'71' => 'Bourgogne',
'89' => 'Bourgogne',
'59' => 'Nord-Pas-de-Calais',
'62' => 'Nord-Pas-de-Calais',
'57' => 'Lorraine',
'54' => 'Lorraine',
'55' => 'Lorraine',
'88' => 'Lorraine',
'67' => 'Alsace',
'68' => 'Alsace',
'25' => 'Franche-Comté',
'39' => 'Franche-Comté',
'70' => 'Franche-Comté',
'90' => 'Franche-Comté',
'44' => 'Pays-de-la-Loire',
'49' => 'Pays-de-la-Loire',
'53' => 'Pays-de-la-Loire',
'72' => 'Pays-de-la-Loire',
'85' => 'Pays-de-la-Loire',
'35' => 'Bretagne',
'22' => 'Bretagne',
'29' => 'Bretagne',
'56' => 'Bretagne',
'86' => 'Poitou-Charentes',
'16' => 'Poitou-Charentes',
'17' => 'Poitou-Charentes',
'79' => 'Poitou-Charentes',
'33' => 'Aquitaine',
'24' => 'Aquitaine',
'40' => 'Aquitaine',
'47' => 'Aquitaine',
'64' => 'Aquitaine',
'31' => 'Midi-Pyrénées',
'09' => 'Midi-Pyrénées',
'12' => 'Midi-Pyrénées',
'32' => 'Midi-Pyrénées',
'46' => 'Midi-Pyrénées',
'65' => 'Midi-Pyrénées',
'81' => 'Midi-Pyrénées',
'82' => 'Midi-Pyrénées',
'87' => 'Limousin',
'19' => 'Limousin',
'23' => 'Limousin',
'69' => 'Rhône-Alpes',
'01' => 'Rhône-Alpes',
'07' => 'Rhône-Alpes',
'26' => 'Rhône-Alpes',
'38' => 'Rhône-Alpes',
'42' => 'Rhône-Alpes',
'73' => 'Rhône-Alpes',
'74' => 'Rhône-Alpes',
'63' => 'Auvergne',
'03' => 'Auvergne',
'15' => 'Auvergne',
'43' => 'Auvergne',
'34' => 'Languedoc-Roussillon',
'11' => 'Languedoc-Roussillon',
'30' => 'Languedoc-Roussillon',
'48' => 'Languedoc-Roussillon',
'66' => 'Languedoc-Roussillon',
'13' => 'Provence-Alpes-Côte-d Azur',
'04' => 'Provence-Alpes-Côte-d Azur',
'05' => 'Provence-Alpes-Côte-d Azur',
'06' => 'Provence-Alpes-Côte-d Azur',
'83' => 'Provence-Alpes-Côte-d Azur',
'84' => 'Provence-Alpes-Côte-d Azur',
'20' => 'Corse');

